// This file is automatically generated.
// Please do not change this file!
export const dark: string;
export const fcas: string;
export const header: string;
export const icon: string;
export const light: string;
export const meta: string;
export const name: string;
export const rank: string;
export const symbol: string;
export const trend: string;
