// This file is automatically generated.
// Please do not change this file!
export const a: string;
export const b: string;
export const c: string;
export const f: string;
export const large: string;
export const rank: string;
export const s: string;
export const slim: string;
export const wrapper: string;
