// This file is automatically generated.
// Please do not change this file!
export const dark: string;
export const legend: string;
export const light: string;
export const line: string;
export const marker: string;
export const related: string;
export const relatedLine: string;
