// This file is automatically generated.
// Please do not change this file!
export const carousel: string;
export const dark: string;
export const dotActive: string;
export const dotItem: string;
export const dots: string;
export const light: string;
export const slide: string;
export const wrapper: string;
