// This file is automatically generated.
// Please do not change this file!
export const change: string;
export const down: string;
export const fcas: string;
export const header: string;
export const link: string;
export const score: string;
export const trend: string;
export const up: string;
export const value: string;
export const wrapper: string;
